name: Generate Snake Animation

on:
  schedule:
    # Runs every 6 hours to update the contribution snake
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: Rajdp-krmkr
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push the changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Change to your default branch
          force: true
